import { selectOptions } from "~/assets/options";
import { type Options } from "~/assets/options";

export interface control {
  component: Component;
  label: string;
  path: string;
  options: Options[];
  selectType?: SelectType;
  showFlagPaths: string[];
  hideFlagPaths: string[];
  master: boolean;
}

export interface Panel {
  element: Element;
  title: string;
  panelLeft: control[];
  panelRight: control[];
}

export enum SelectType {
  opacity = "opacities",
  fontWeight = "fontWeights",
  borderWidth = "borderWidths",
  avatarSize = "avatarSizes",
}

export enum Component {
  ImageUpLoader = "ImageUpLoader",
  ColorPicker = "ColorPicker",
  Select = "Select",
  FontSelect = "FontSelect",
  Number = "Number",
  Switch = "Switch",
  DateItemAdder = "DateItemAdder",
  Input = "Input",
}

export enum Element {
  background = "background",
  "outer circle" = "outerCircle",
  "month names" = "monthNames",
  "date items" = "dateItems",
  center = "center",
}

let elementPanels: Panel[] = Array.from([
  {
    element: Element.background,
    title: "background",
    panelLeft: [
      {
        component: Component.Switch,
        label: "image",
        path: "image.active",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },

      // {
      //   component: Component.ImageUpLoader,
      //   label: "upload image",
      //   path: "image",
      //   options: [],
      //   showFlagPaths: [],
      //   hideFlagPaths: [],
      //   master: false,
      // },
    ],
    panelRight: [
      {
        component: Component.Switch,
        label: "overlay",
        options: [],
        path: "overlay.active",
        showFlagPaths: [],
        master: false,
        hideFlagPaths: [],
      },
      {
        component: Component.Select,
        label: "transparency",
        path: "overlay.opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        hideFlagPaths: [],
        showFlagPaths: ["overlay.active"],
        master: false,
      },
      // {
      //   component: Component.Number,
      //   label: "backdropBlur",
      //   path: "overlay.backdropBlur",
      //   options: [],
      //   hideFlagPaths: [],
      //   showFlagPaths: ["overlay.active"],
      //   master: false,
      // },
      {
        component: Component.ColorPicker,
        label: "colour",
        path: "overlay.color",
        options: [],
        selectType: SelectType.opacity,
        hideFlagPaths: [],
        showFlagPaths: ["overlay.active"],
        master: false,
      },

      {
        component: Component.Switch,
        label: "radial gradient",
        path: "overlay.radialGradient.active",
        options: [],
        showFlagPaths: ["overlay.active"],
        hideFlagPaths: [],
        master: false,
      },

      {
        component: Component.ColorPicker,
        label: "center colour",
        path: "overlay.radialGradient.centerColor",
        options: [],
        showFlagPaths: ["overlay.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "center colour size",
        path: "overlay.radialGradient.centerSize",
        options: [],
        showFlagPaths: ["overlay.active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    master: false,
  },
  {
    element: Element["outer circle"],
    title: "outer circle",
    panelLeft: [
      {
        component: Component.Number,
        label: "size",
        path: "ratio",
        options: [],
        hideFlagPaths: [],
        showFlagPaths: [],
        master: true,
      },

      {
        component: Component.ColorPicker,
        label: "color",
        path: "color",
        options: [],
        hideFlagPaths: [],
        showFlagPaths: ["active"],
        master: false,
      },
      {
        component: Component.Select,
        label: "transparency",
        path: "opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        hideFlagPaths: [],
        showFlagPaths: ["active"],
        master: false,
      },
      {
        component: Component.Number,
        label: "backdrop blur",
        path: "backdropBlur",
        options: [],
        hideFlagPaths: [],
        showFlagPaths: ["active"],
        master: false,
      },
    ],
    panelRight: [
      {
        component: Component.Switch,
        label: "border",
        path: "border.active",
        options: [],
        selectType: SelectType.opacity,
        hideFlagPaths: [],
        showFlagPaths: ["active"],
        master: false,
      },
      {
        component: Component.Number,
        label: "border width",
        path: "border.width",
        options: [],
        selectType: SelectType.opacity,
        hideFlagPaths: [],
        showFlagPaths: ["border.active"],
        master: false,
      },

      {
        component: Component.ColorPicker,
        label: "border color",
        path: "border.color",
        options: [],
        selectType: SelectType.opacity,
        showFlagPaths: ["border.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Select,
        label: "border transparency",
        path: "border.opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        showFlagPaths: ["border.active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    master: false,
  },
  {
    element: Element["month names"],
    title: "month names",
    panelLeft: [
      {
        component: Component.Number,
        label: "size",
        path: "ratio",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.FontSelect,
        label: "font",
        path: "fontFamily",
        options: [],
        selectType: SelectType.opacity,
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "font size",
        path: "fontSize",
        options: [],
        selectType: SelectType.opacity,
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    panelRight: [
      {
        component: Component.Select,
        label: "transparency",
        path: "opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "text color",
        path: "color",
        options: [],
        selectType: SelectType.opacity,
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    master: false,
  },
  {
    element: Element["date items"],
    title: "date items",
    panelLeft: [
      {
        component: Component.FontSelect,
        label: "font",
        path: "text.fontFamily",
        options: [],
        hideFlagPaths: [],
        showFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "font size",
        path: "text.fontSize",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "text colour",
        path: "text.color",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Select,
        label: "item shape",
        path: "itemBorder.radius",
        options: selectOptions.avatarShapes,
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },

      {
        component: Component.Switch,
        label: "item background",
        path: "bgColor.active",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "background colour",
        path: "bgColor.color",
        options: [],
        showFlagPaths: ["bgColor.active"],
        hideFlagPaths: [],
        master: false,
      },

      {
        component: Component.Select,
        label: "background transparency",
        path: "bgColor.opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        showFlagPaths: ["bgColor.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "backdrop blur",
        path: "bgColor.backdropBlur",
        options: [],
        showFlagPaths: ["bgColor.active"],
        hideFlagPaths: [],
        master: false,
      },

      {
        component: Component.Switch,
        label: "item outlines",
        path: "itemBorder.active",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "item border color",
        path: "itemBorder.color",
        options: [],
        showFlagPaths: ["itemBorder.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "item border width",
        path: "itemBorder.width",
        options: [],
        showFlagPaths: ["itemBorder.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Select,
        label: "item border transparency",
        path: "itemBorder.opacity",
        options: selectOptions[SelectType.opacity],
        showFlagPaths: ["itemBorder.active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    panelRight: [
      {
        component: Component.Switch,
        label: "avatar",
        path: "avatar",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },

      {
        component: Component.Select,
        label: "avatar shape",
        path: "avatarBorder.radius",
        options: selectOptions.avatarShapes,
        showFlagPaths: ["avatar"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "avatar size",
        path: "avatarSize",
        options: [],
        showFlagPaths: ["avatar"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Switch,
        label: "avatar border",
        path: "avatarBorder.active",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "avatar border color",
        path: "avatarBorder.color",
        options: [],
        showFlagPaths: ["avatarBorder.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "avatar border width",
        path: "avatarBorder.width",
        options: [],
        showFlagPaths: ["avatarBorder.active"],
        hideFlagPaths: [],
        master: false,
      },

      {
        component: Component.Select,
        label: "avatar border transparency",
        path: "avatarBorder.opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        showFlagPaths: ["avatarBorder.active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    master: false,
  },
  {
    element: Element.center,
    title: "center",
    panelLeft: [
      {
        component: Component.Switch,
        label: "center",
        path: "active",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: true,
      },
      {
        component: Component.Input,
        label: "center text",
        path: "copy",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.FontSelect,
        label: "font",
        path: "text.fontFamily",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "font size",
        path: "text.fontSize",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "text color",
        path: "text.color",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Select,
        label: "text transparency",
        path: "text.opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "background color",
        path: "background.color",
        options: [],
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Select,
        label: "background transparency",
        path: "background.opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        showFlagPaths: ["active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    panelRight: [
      {
        component: Component.Switch,
        label: "border",
        path: "border.active",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ColorPicker,
        label: "border color",
        path: "border.color",
        options: [],
        showFlagPaths: ["border.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.ImageUpLoader,
        label: "upload background image",
        path: "back",
        options: [],
        showFlagPaths: [],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Number,
        label: "border width",
        path: "border.width",
        options: [],
        showFlagPaths: ["border.active"],
        hideFlagPaths: [],
        master: false,
      },
      {
        component: Component.Select,
        label: "border transparency",
        path: "border.opacity",
        options: selectOptions[SelectType.opacity],
        selectType: SelectType.opacity,
        showFlagPaths: ["border.active"],
        hideFlagPaths: [],
        master: false,
      },
    ],
    master: false,
  },
]);

export default elementPanels;
